name: "Deploy to GitHub Pages"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --no-fund
      - name: Build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --no-fund
      - name: Build
        run: npm run build
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
